### ISSUE TITLE
sbt-bintray complains about new license

### ISSUE THREAD

**Issue by SethTisue** [bmc/grizzled-scala#19]
seen in Scala 2.13 community build:

```
[grizzled] Publishing: default-sbt-project
[grizzled] [error] java.lang.RuntimeException: One or more of the defined licenses were not among the following allowed licenses
[grizzled] [error]  AFL-2.1, AFL-3.0, AGPL-V3, APL-1.0, APSL-2.0, Apache-1.0, Apache-1.1, Apache-2.0, Artistic-License-2.0, Attribution, BSD, BSD 2-Clause, BSD 3-Clause, BSD New, BSD Simplified, BSL-1.0, Bouncy-Castle, CA-TOSL-1.1, CC0-1.0, CDDL-1.0, CDDL-1.1, CPAL-1.0, CPL-1.0, CPOL, CPOL-1.02, CUAOFFICE-1.0, CeCILL-1, CeCILL-2, CeCILL-2.1, CeCILL-B, CeCILL-C, Codehaus, Copyfree, Day, Day-Addendum, ECL2, EPL-1.0, EPL-2.0, EUDATAGRID, EUPL-1.1, Eiffel-2.0, Entessa-1.0, Facebook-Platform, Fair, Frameworx-1.0, GPL-2.0, GPL-2.0+CE, GPL-3.0, Go, HSQLDB, Historical, IBMPL-1.0, IPAFont-1.0, ISC, IU-Extreme-1.1.1, ImageMagick, JA-SIG, JSON, JTidy, LGPL-2.1, LGPL-3.0, LPPL-1.0, Libpng, Lucent-1.02, MIT, MPL-2.0, MS-PL, MS-RL, MirOS, Motosoto-0.9.1, Mozilla-1.1, Multics, NASA-1.3, NAUMEN, NOSL-3.0, NTP, NUnit-2.6.3, NUnit-Test-Adapter-2.6.3, Nethack, Nokia-1.0a, OCLC-2.0, OSL-3.0, OpenLDAP, OpenSSL, Openfont-1.1, Opengroup, PHP-3.0, PostgreSQL, Public Domain, Public Domain - SUN, PythonPL, PythonSoftFoundation, QTPL-1.0, RPL-1.5, Real-1.0, RicohPL, SUNPublic-1.0, Scala, SimPL-2.0, Sleepycat, Sybase-1.0, TMate, Unlicense, UoI-NCSA, VIM License, VovidaPL-1.0, W3C, WTFPL, Xnet, ZLIB, ZPL-2.0, wxWindows
[grizzled] [error] 	at scala.sys.package$.error(package.scala:30)
[grizzled] [error] 	at bintray.Bintray$.ensureLicenses(Bintray.scala:48)
```

but it's also reproducible outside dbuild just by running `publish`

it's avoidable by setting `bintrayOmitLicense` to `true`, if you want

**Comment by SethTisue** [comment]
Bintray is dead.
